import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  parallel: ReactNode;
};

const RootLayout = ({ children, parallel }: Props) => {
  return (
    <html lang="ja">
      <body>
        {children}
        <div>{parallel}</div>
      </body>
    </html>
  );
};

export default RootLayout;
